/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Buffer */

#ifndef _Included_Buffer
#define _Included_Buffer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
